### ISSUE TITLE
Rename the default branch of this repo from `master` to `main`

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-readiness#25]
See https://github.com/ampproject/amphtml/issues/32195 for more details

**Comment by philkrie** [comment]
@jeffjose is this something you can do? When I go to the branch view, I am unable to edit "master".

![image](https://user-images.githubusercontent.com/8532477/114088300-bcb68b80-9869-11eb-9b19-6b5d9a66ab6f.png)

As you can see the second branch in that image has an edit icon, not sure if this is because of permissions.

**Comment by tobie** [comment]
+1 from me, but I don't have admin access to this repo.

**Comment by rsimha** [comment]
I have admin access and just renamed the branch. Hopefully this didn't break anything. 🤞

![image](https://user-images.githubusercontent.com/26553114/114094090-e54e7d80-9889-11eb-8df8-5d00de79f58a.png)
